### ISSUE TITLE
Problem loading dependent libraries

### ISSUE THREAD

**Issue by martingale** [martingale/Rmatriksdata#1]
`detach(package:http)`
`detach(package:Rmatriksdata)`
`library(Rmatriksdata)`
 `Rmatriksdata::matriksData("GARAN","trade","2015-12-31","2015-12-31",period="1hour")`
`Error: could not find function "GET"`

**Comment by vc-k** [comment]
Thank you. Its fixed.

**Comment by martingale** [comment]
Not fixed but the error message has changed to 
`Loading required package: httr
Failed with error:  ‘object 'jsonlite' not found’
Error: could not find function "GET"`

**Comment by vc-k** [comment]
Its caused by wrong require usage.

**Comment by martingale** [comment]
Not solved! 
` Rmatriksdata::matriksSymbols()
Error in Rmatriksdata::matriksSymbols() : could not find function "GET"`

**Comment by vc-k** [comment]
namespace updated
